# Install a Azure CLi role
- name: azure-cli
  src: dfarrell07.opendaylight

# Install a Jenkins role 
- name: jenkins
  src: geerlingguy.jenkins

# Install a terraform 
- name: terraform
  src: andrewrothstein.terraform
